### ISSUE TITLE
fix a bug in reading correct jet pt

### ISSUE THREAD

**Issue by mpresill** [mpresill/LatinoAnalysis#6] opened 2021-12-13 13:48 UTC
there is bug in reading fj pt.
https://github.com/latinos/LatinoAnalysis/blob/master/NanoGardener/python/modules/FatJetMaker.py#L126 
we would have to change:
 `fj.pt ==>  fj.pt_nom`
Comment: ft.pt method did not read the jet pt as recalculated from jetnanoaodtools (with updated JEC, ...).

**Comment by SiewYan** [comment] 2021-12-14 11:53
You are referring to master branch of LatinoAnalysis..

I think this is not a bug: https://github.com/latinos/LatinoAnalysis/blob/UL_production/NanoGardener/python/modules/FatJetMaker.py#L126

fj.pt access the original pt if no suffix (_up,_down) are found.

It is alright for now because we are not processing Up and DOWN branches (we suppressed it [*]) , which is what Tomas's code is doing.

[*] https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/modules/FatJetMaker.py#L58-L62

**Comment by SiewYan** [comment] 2022-02-03 03:14
closing this issue, as it is clarified that the variation is performed in third step of the UL production.

**Closed as completed by SiewYan** 2022-02-03 03:14 UTC
